<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find robotv1_description)/urdf/utilities.xacro"/>
  <xacro:include filename="$(find robotv1_description)/urdf/gripper.xacro"/>
  <xacro:include filename="$(find robotv1_description)/urdf/arm.gazebo"/>

  <xacro:property name="lenXUpperArm" value="0.02"/>
  <xacro:property name="lenYUpperArm" value="0.06"/>
  <xacro:property name="lenZUpperArm" value="0.12"/>
  
  <xacro:property name="lenXLowerArm" value="0.02"/>
  <xacro:property name="lenYLowerArm" value="0.04"/>
  <xacro:property name="lenZLowerArm" value="0.07"/>
  
  <xacro:property name="lenXWrist" value="0.04"/>
  <xacro:property name="lenYWrist" value="0.06"/>
  <xacro:property name="lenZWrist" value="0.03"/>

 <xacro:macro name="arm" params="prefix" >
    <joint name="${prefix}ShoulderJoint" type="revolute" >
      <parent link="torso"/>
      <child link="${prefix}UpperArm"/>
      <origin xyz="0 0 ${lenZTorso + jointOffset}"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0"/>
      <limit effort="0.2" velocity="1.0" lower="${-pi/2}" upper="${pi/2}" />
    </joint>

   <link name="${prefix}UpperArm" >
     <visual>
       <origin xyz="0 0 ${lenZUpperArm/2.0}" rpy="0 0 0"/>
       <geometry>
         <box size="${lenXUpperArm} ${lenYUpperArm} ${lenZUpperArm}"/>
       </geometry>
       <material name="orange"/>
     </visual>
     <inertial>
      <origin xyz="0 0 ${lenZUpperArm/2.0}"/>
       <xacro:box_inertia  lenx="${lenXUpperArm}" leny="${lenYUpperArm}" lenz="${lenZUpperArm}" />
     </inertial>
     <collision>
       <origin xyz="0 0 ${lenZUpperArm/2.0}" rpy="0 0 0"/>
       <geometry>
         <box size="${lenXUpperArm} ${lenYUpperArm} ${lenZUpperArm}"/>
       </geometry>
    </collision>
  </link>
  
  <joint name="${prefix}ElbowJoint" type="revolute" >
    <parent link="${prefix}UpperArm"/>
    <child link="${prefix}LowerArm"/>
    <origin xyz="0 0 ${lenZUpperArm + jointOffset}"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0"/>
    <limit effort="0.2" velocity="1.0" lower="0" upper="${pi}" />
  </joint>

  <link name="${prefix}LowerArm">
    <visual>
      <origin xyz="0 0 ${lenZLowerArm/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${lenXLowerArm} ${lenYLowerArm} ${lenZLowerArm}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 ${lenZLowerArm/2.0}"/>
      <xacro:box_inertia  lenx="${lenXLowerArm}" leny="${lenYLowerArm}" lenz="${lenZLowerArm}" />
    </inertial>
    <collision>
      <origin xyz="0 0 ${lenZLowerArm/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${lenXLowerArm} ${lenYLowerArm} ${lenZLowerArm}"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="${prefix}WristJoint" type="revolute" >
    <parent link="${prefix}LowerArm"/>
    <child link="${prefix}Wrist"/>
    <origin xyz="0 0 ${lenZLowerArm + jointOffset}"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0"/>
    <limit effort="0.2" velocity="1.0" lower="${-pi/2}" upper="${pi/2}" />
  </joint>

  <link name="${prefix}Wrist" >
    <visual>
      <origin xyz="0 0 ${lenZWrist/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${lenXWrist} ${lenYWrist} ${lenZWrist}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 ${lenZWrist/2.0}"/>
      <xacro:box_inertia  lenx="${lenXWrist}" leny="${lenYWrist}" lenz="${lenZWrist}" />
    </inertial>
    <collision>
      <origin xyz="0 0 ${lenZWrist/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${lenXWrist} ${lenYWrist} ${lenZWrist}"/>
      </geometry>
    </collision>
  </link>
  
  <!--
  <joint name="${prefix}_wrist_2_joint" type="fixed" >
    <parent link="${prefix}Wrist"/>
    <child link="${prefix}_gripper"/>
    <origin xyz="0 0 ${lenZWrist}"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0"/>
    <limit effort="0.2" velocity="1.0" lower="${-pi/2}" upper="${pi/2}" />
  </joint>

  <xacro:gripper prefix="${prefix}"/>
  -->
  <transmission name="${prefix}ShoulderTransmission">
    <type> transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}ShoulderJoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${prefix}ShoulderMotor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="${prefix}ElbowJointTransmission">
    <type> transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}ElbowJoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${prefix}ElbowJointMotor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="${prefix}WristJointTran">
    <type> transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}WristJoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${prefix}WristJointMotor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <!--
  <transmission name="${prefix}_wrist_2_joint_tran">
    <type> transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}_wrist_2_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${prefix}_wrist_2_joint_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  -->

  <xacro:arm_gazebo_reference prefix="${prefix}"/>

</xacro:macro>



</robot> 
