<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <!--Constant for the robotv1-->
  <xacro:include filename="$(find robotv1_description)/urdf/leg.gazebo" />

  <xacro:property name="lenXUpperLeg" value="0.06"/>
  <xacro:property name="lenYUpperLeg" value="0.06"/>
  <xacro:property name="lenZUpperLeg" value="0.15"/>

  <xacro:property name="lenXLowerLeg" value="0.06"/>
  <xacro:property name="lenYLowerLeg" value="0.06"/>
  <xacro:property name="lenZLowerLeg" value="0.10"/>
  
  <xacro:property name="lenXFoot" value="0.1"/>
  <xacro:property name="lenYFoot" value="0.04"/>
  <xacro:property name="lenZFoot" value="0.02"/>

  <xacro:property name="basePosition" value="${lenZUpperLeg+lenZLowerLeg+lenZLowerLeg+lenZFoot}"/>

  <xacro:macro name="leg" params="prefix reflect" >
    <joint name="${prefix}HipJoint" type="revolute" >
      <parent link="pelvis"/>
      <child link="${prefix}UpperLeg"/>
      <origin xyz="0 ${reflect*(lenYUpperLeg/2.0 + lenYPelvis/2.0 + jointOffset)} 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0"/>
      <limit effort="2" velocity="1.0" lower="${-pi/2}" upper="${pi/2}" />
    </joint>
    
    <link name="${prefix}UpperLeg" >
      <visual>
        <origin xyz="0 0 ${-1*lenZUpperLeg/2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="${lenXUpperLeg} ${lenYUpperLeg} ${lenZUpperLeg}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <inertial>
        <origin xyz="0 0 ${-1*lenZUpperLeg/2.0}"/>
        <xacro:box_inertia  lenx="${lenXUpperLeg}" leny="${lenYUpperLeg}" lenz="${lenZUpperLeg}" />
      </inertial>
      <collision>
        <origin xyz="0 0 ${-1*lenZUpperLeg/2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="${lenXUpperLeg} ${lenYUpperLeg} ${lenZUpperLeg}"/>
        </geometry>
     </collision>
   </link>

    <joint name="${prefix}KneeJoint" type="revolute" >
      <parent link="${prefix}UpperLeg"/>
      <child link="${prefix}LowerLeg"/>
      <origin xyz="0 0 ${-lenZUpperLeg - jointOffset}" rpy = "0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0"/>
      <limit effort="2" velocity="1.0" lower="0" upper="${7*pi/8}" />
    </joint>

    <link name="${prefix}LowerLeg" >
      <visual>
        <origin xyz="0 0 ${-lenZLowerLeg/2.0}" rpy="0 0 0"/>
        <geometry>
         <box size="${lenXLowerLeg} ${lenYLowerLeg} ${lenZLowerLeg}"/>
        </geometry>
        <material name="orange"/>
      </visual>
    <inertial>
      <origin xyz="0 0 ${-1*lenZLowerLeg/2.0}"/>
      <xacro:box_inertia  lenx="${lenXLowerLeg}" leny="${lenYLowerLeg}" lenz="${lenZLowerLeg}" />
    </inertial>    
     <collision>
       <origin xyz="0 0 ${-lenZLowerLeg/2.0}" rpy="0 0 0"/>
       <geometry>
         <box size="${lenXLowerLeg} ${lenYLowerLeg} ${lenZLowerLeg}"/>
       </geometry>
     </collision>
    </link>

    <joint name="${prefix}AnkleJoint" type="revolute" >
      <parent link="${prefix}LowerLeg"/>
      <child link="${prefix}Foot"/>
      <origin xyz="0 0 ${-lenZLowerLeg - jointOffset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0"/>
      <limit effort="2" velocity="1.0" lower="${-pi/4}" upper="${pi/4}" />
    </joint>

    <link name="${prefix}Foot" >
      <visual>
        <origin xyz="${lenXFoot/2} 0 ${-lenZFoot/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${lenXFoot} ${lenYFoot} ${lenZFoot}"/>
        </geometry>
        <material name="orange"/>
      </visual>
     <inertial>
       <origin xyz="${lenXFoot/2.0} 0 ${-lenZFoot/2.0}"/>
       <xacro:box_inertia  lenx="${lenXFoot}" leny="${lenYFoot}" lenz="${lenZFoot}" />
     </inertial>
     <collision>
       <origin xyz="${lenXFoot/2} 0 ${-lenZFoot/2}" rpy="0 0 0"/>
       <geometry>
          <box size="${lenXFoot} ${lenYFoot} ${lenZFoot}"/>
       </geometry>
     </collision>
    </link>

    <transmission name="${prefix}HipTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}HipJoint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}HipMotor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  
    <transmission name="${prefix}KneeTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}KneeJoint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}KneeMotor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    
    <transmission name="${prefix}AnkleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}AnkleJoint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}AnkleMotor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    
   <xacro:leg_gazebo_reference prefix="${prefix}"/>
 </xacro:macro>

</robot>
