<?xml version="1.0"?>
<robot name="robotv1" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find robotv1_description)/urdf/utilities.xacro"/>
<xacro:include filename="$(find robotv1_description)/urdf/lower_body.xacro"/>
<xacro:include filename="$(find robotv1_description)/urdf/upper_body.xacro"/>
<xacro:include filename="$(find robotv1_description)/materials/materials.xacro" />
<!-- only gazebo plug-in -->
<xacro:include filename="$(find robotv1_description)/urdf/robotv1.gazebo"/>

<link name="world"/>

<joint name="fixed_world" type="fixed">
  <origin xyz="0 0 ${basePosition}" rpy="0 0 0"/>
  <parent link="world" />
  <child link="pelvis" />
</joint>

<joint name="pelvisTorsoJoint" type="fixed">
  <origin xyz="0 0 ${lenZPelvis/2.0 + jointOffset}"/>
  <parent link="pelvis"/>
  <child link="torso"/>
</joint>

</robot>
