<robot name="robotv1" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find robotv1_description)/urdf/utilities.xacro"/>
  <xacro:include filename="$(find robotv1_description)/urdf/arm.xacro"/>

  <xacro:property name="lenZTorso" value=".1"/>
  <xacro:property name="lenYTorso" value=".05"/>
  <xacro:property name="lenXTorso" value=".05"/>

  <link name="torso">
    <visual>
      <origin xyz="0 0 ${lenZTorso/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${lenXTorso} ${lenYTorso} ${lenZTorso}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${lenZTorso/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${lenXTorso} ${lenYTorso} ${lenZTorso}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${lenZTorso}"/>
      <xacro:box_inertia lenx="${lenXTorso}" leny="${lenYTorso}" lenz="${lenZTorso}"/>
    </inertial>
  </link>

  <xacro:arm prefix=""/>
</robot>
