robotv1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  shoulder_controller:
    type: effort_controllers/JointPositionController
    joint: ShoulderJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  elbow_controller:
    type: effort_controllers/JointPositionController
    joint: ElbowJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  wrist_controller:
    type: effort_controllers/JointPositionController
    joint: WristJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
   
