robotv1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  left_hip_controller:
    type: effort_controllers/JointPositionController
    joint: leftHipJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_knee_controller:
    type: effort_controllers/JointPositionController
    joint: leftKneeJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  left_ankle_controller:
    type: effort_controllers/JointPositionController
    joint: leftAnkleJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
   
  right_hip_controller:
    type: effort_controllers/JointPositionController
    joint: rightHipJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_knee_controller:
    type: effort_controllers/JointPositionController
    joint: rightKneeJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  right_ankle_controller:
    type: effort_controllers/JointPositionController
    joint: rightAnkleJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
